// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPIxneDIbRQorP_D-djEnBS2_hJmzFikU',
    appId: '1:685596783446:web:6ad6a930e34b1cd25b5cf7',
    messagingSenderId: '685596783446',
    projectId: 'tugasbesarpbb-5c8d2',
    authDomain: 'tugasbesarpbb-5c8d2.firebaseapp.com',
    storageBucket: 'tugasbesarpbb-5c8d2.firebasestorage.app',
    measurementId: 'G-369V47XFG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9sHfzqg2x1he-GLYJhWJ9quYNpXhpcrg',
    appId: '1:685596783446:android:a15487226a29ff195b5cf7',
    messagingSenderId: '685596783446',
    projectId: 'tugasbesarpbb-5c8d2',
    storageBucket: 'tugasbesarpbb-5c8d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqCtIMKoSE76rCe_qpnME568Or-SRSgTI',
    appId: '1:685596783446:ios:3d55ff20e250acdc5b5cf7',
    messagingSenderId: '685596783446',
    projectId: 'tugasbesarpbb-5c8d2',
    storageBucket: 'tugasbesarpbb-5c8d2.firebasestorage.app',
    iosBundleId: 'com.example.tapbbAsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqCtIMKoSE76rCe_qpnME568Or-SRSgTI',
    appId: '1:685596783446:ios:3d55ff20e250acdc5b5cf7',
    messagingSenderId: '685596783446',
    projectId: 'tugasbesarpbb-5c8d2',
    storageBucket: 'tugasbesarpbb-5c8d2.firebasestorage.app',
    iosBundleId: 'com.example.tapbbAsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPIxneDIbRQorP_D-djEnBS2_hJmzFikU',
    appId: '1:685596783446:web:331131b4232130255b5cf7',
    messagingSenderId: '685596783446',
    projectId: 'tugasbesarpbb-5c8d2',
    authDomain: 'tugasbesarpbb-5c8d2.firebaseapp.com',
    storageBucket: 'tugasbesarpbb-5c8d2.firebasestorage.app',
    measurementId: 'G-3LNP9686KK',
  );
}
